 [platformio]
default_envs = esp32-s3-devkitc-1 ; Chọn môi trường mặc định muốn build/upload

; ==========================================
; 1. ESP32-S3 (Beacon 1) - Native USB
; ==========================================
[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1

; ==========================================
; 2. ESP32 Thường / DevKit V1 (Beacon 2) - Cổng UART/COM chuẩn
; ==========================================
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; ==========================================
; 3. ESP32-C3 Super Mini (Beacon 3) - BẮT BUỘC NATIVE USB
; ==========================================
[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_protocol = esptool
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1